### ISSUE TITLE
Error is not generated if no hosts are configured

### ISSUE THREAD

**Issue by joshdk** [appleboy/drone-ssh#114]
There is a usability edge-case that is manifested by  [plugin.go line #130](https://github.com/appleboy/drone-ssh/blob/master/plugin.go#L130);

If you have a `user`/`PLUGIN_USER` configured but no `host`/`PLUGIN_HOST`, no error will be generated. Specifically the "[missing server **or** host](https://github.com/appleboy/drone-ssh/blob/master/plugin.go#L15)" error.

This can be very confusing if you (incorrectly/accidentally) configured no hosts, and have a script that outputs nothing. All you see is the `Successfully executed commands to all host.` message, but no actions have **actually** been taken.

I'm not sure if this is a bug, because maybe running on a (dynamic generated?) list of 0 hosts is something you would want to do. If is is a bug, the `&&` probably just needs to be flipped to an `||` in the conditional.

**Comment by appleboy** [comment]
Please try the latest version.
