### ISSUE TITLE
 connect: no route to host

### ISSUE THREAD

**Issue by meodemsao** [appleboy/drone-ssh#142]
i have issues when using drone and ssh target server in the same server

`dial tcp ********:3001: connect: no route to host`

but in another project it's run normal

**Comment by appleboy** [comment]
Please provide your config.

**Comment by XiaoHanChina** [comment]
Run the code bellow on your target server.
`firewall-cmd --zone=public --add-port=3001/tcp --permanent`

**Comment by appleboy** [comment]
not drone-ssh issue.
