### ISSUE TITLE
script output listed as err

### ISSUE THREAD

**Issue by ff4500** [appleboy/drone-ssh#143]
This is more of an annoyance than anything else, but I wondered if there was a quick fix to the way that I was calling a docker-compose restart via script. I put the `echo` cmd in there to make sure that the output was accurately showing an `out` status on a simple cmd.

In the script section of my pipeline step, I have the following to restart docker-compose:

```
settings:
    script:
        echo docker-compose up -d
        docker-compose up -d
```

In my step output in Drone (for drone-ssh), I'm getting:
```
out: docker-compose up -d 
err: Creating examplesite.com ... 
err: Creating examplesite.com ... done
```

Even though it throws an `err` on each output step of the compose cmd, it still works fine. I only get this when running through a pipeline step, not on the command line, obviously. Ideas here, or is this a legitimate bug?

**Comment by terreb** [comment]
Same here, shows err: for every message. Also, it doesn't interrupt if any script step finishes with status=1, but keeps going.

**Comment by appleboy** [comment]
Example configuration for stoping script after first failure:

```diff
  image: appleboy/drone-ssh
  settings:
    host: foo.com
    username: root
    password: 1234
    port: 22
+   script_stop: true
    script:
      - mkdir abc/def/efg
      - echo "you can't see the steps."
```
