### ISSUE TITLE
Connect the Mac computer, command tty to return not a tty

### ISSUE THREAD

**Issue by shenqidebaozi** [appleboy/drone-ssh#154]
Hello, I hope you can help me solve the problem

Connect the Mac computer, command tty to return not a tty,but my computer connect this Mac computer tty ,return ttys001. And after connecting to the Mac, there is no required environment variable
![image](https://user-images.githubusercontent.com/35397691/79004066-8f67cc80-7b86-11ea-8c9e-398e2500b4a6.png)
![image](https://user-images.githubusercontent.com/35397691/79004114-a7d7e700-7b86-11ea-939d-8001c6c0fb42.png)

**Comment by shenqidebaozi** [comment]
Environment variables are also manually declared through export
![image](https://user-images.githubusercontent.com/35397691/79004342-2765b600-7b87-11ea-9c62-0815bf575d9e.png)

**Comment by shenqidebaozi** [comment]
Linux doesn't have this problem

**Comment by appleboy** [comment]
This is not drone-ssh plugin issuer. Right?

**Comment by appleboy** [comment]
fixed in b34fffd. Try `--request-pty` flag.
