### ISSUE TITLE
when use "," in the script , it produce a newline

### ISSUE THREAD

**Issue by smally10** [appleboy/drone-ssh#173]
For example
```
      script:
        - sed -i 's/abc/abc,/g' a.txt

```
there will be  an  error

**Comment by smally10** [comment]
`  - name: ssh
    image: appleboy/drone-ssh
    **# step 1: ​define env**
   ​environment:
     ​COMMA: ","
   ​settings:
     ​host:
     ​port:
     ​username:
     ​key:
     **​# step 2: import evn**
     ​envs:
       ​- COMMA
     script:
        **# step 3: use the env,
        # two $, used to avoid pre-processing** 
        - echo "$${COMMA}"`

**Comment by appleboy** [comment]
Please try v1.6.7 version.
