### ISSUE TITLE
ssh.ParsePrivateKey: ssh: no key found

### ISSUE THREAD

**Issue by fivenull** [appleboy/drone-ssh#179]
Hello, I have a problem
i use password ，is ok ,but use ssh_key failure

2022/03/18 08:47:59 ssh.ParsePrivateKey: ssh: no key found
2022/03/18 08:47:59 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by appleboy** [comment]
post your config?

**Comment by fehnomenal** [comment]
I'm having the same issue running the github action.

Config:
![image](https://user-images.githubusercontent.com/9959940/212058815-54cac292-ae35-4f46-bac2-ce0687108978.png)

The debug output prints:
![image](https://user-images.githubusercontent.com/9959940/212059022-a6fee863-bc9a-402e-a63d-04c5889e092b.png)
so it seems to get the key

The key is also passed to docker (`-e "INPUT_KEY"`) and works when connecting locally.
