### ISSUE TITLE
Update broke multiple script section

### ISSUE THREAD

**Issue by Poldan** [appleboy/drone-ssh#213]
script:
        - foo
        - bar
        - baz
Now executing as "foo,bar,baz".

**Comment by tifeit** [comment]
Same here

```
    image: 'appleboy/drone-ssh:latest'
...
    script:
      - 'set -e'
      - 'export ENV=asdf'
```

ends up with

```
set -e,export ENV=asdf
```


The workaround that worked for me - switching to prev. version

```
    image: 'appleboy/drone-ssh:1.6.6-linux-amd64'
...
    script:
      - 'set -e'
      - 'export ENV=asdf'
```

**Comment by theonedemon** [comment]
some problem, please delete 1.6.7 version is broken

**Comment by appleboy** [comment]
Hi All,

I removed the old tag v1.6.7 and created a new tag v1.6.7 to overwrite it.
