### ISSUE TITLE
Upload multiple CPU architectures under the same docker tag

### ISSUE THREAD

**Issue by albertyw** [appleboy/drone-ssh#216]
drone-ssh's docker tags in hub.docker.com [are specific to single CPU architectures](https://hub.docker.com/r/appleboy/drone-ssh/tags?page=1&name=1.6.7) such as `1-linux-arm64` and `1-linux-amd64`.  This means that drone configs are not portable between arm64 and amd64 architectures and different tags must be selected based on where the docker container is run.

Can you instead follow the pattern that [several other docker images have](https://hub.docker.com/_/python/tags) which is to group multiple CPU architectures under the same docker tag and letting docker clients automatically determine which CPU architecture to pull?

**Comment by albertyw** [comment]
Looks like this is now done by https://github.com/appleboy/drone-ssh/commit/d0ed2bb2fbd0e68efe8da3db2df142c0ae4b8566

**Comment by appleboy** [comment]
@albertyw Yes, you are right. Please https://github.com/appleboy/drone-ssh/releases/tag/v1.6.9 version.
