### ISSUE TITLE
The latest version of nas cannot be used, only 1.6.4 can be used

### ISSUE THREAD

**Issue by bbhxwl** [appleboy/drone-ssh#218]
The latest version of nas cannot be used, only 1.6.4 can be used

**Comment by garymoon** [comment]
In lieu of opening another ticket, I assume OP is referring to [this issue](https://github.com/appleboy/drone-scp/issues/146) that also affects drone-scp.

**Comment by garymoon** [comment]
For now you can either use `appleboy/drone-ssh:1.6.4` to pin the last release with an amd64 image, or use `appleboy/drone-ssh:linux-amd64` for the latest available amd64 image.

**Comment by appleboy** [comment]
@garymoon Fixed. Please try the latest tag.

**Comment by garymoon** [comment]
I can confirm this is fixed, thanks @appleboy!

**Comment by appleboy** [comment]
@garymoon Thanks.
