### ISSUE TITLE
Using comma in commands

### ISSUE THREAD

**Issue by ODAEL** [appleboy/drone-ssh#220]
Hi!
Do I understand it right that after reverting #212 we now have this comma problem (#60  #177) again?
Do we have an idea or workaround (better than using `$COMMA` env param) to fix it now?

I still have this problem on versions 1.6.6, 1.6.7.

**Comment by appleboy** [comment]
@ODAEL Yes. I will re-open related the issue and think about how to fix it.

**Comment by ODAEL** [comment]
Thank you. Should we close this issue?

**Comment by appleboy** [comment]
OK. Keep tracking in #60 and #177
