### ISSUE TITLE
Question on optimal way to use in Gitlab

### ISSUE THREAD

**Issue by localpath** [appleboy/drone-ssh#227]
Love this tool. QQ. I've used it in Github via the publish action and I'm using it in Gitlab via docker and a dind service to just run the container and do some ssh proxy. Is there a better way maybe to build a custom docker image that contains the binaries of the ssh utility and avoid using docker in docker?

THanks!

**Comment by appleboy** [comment]
try the binary https://github.com/appleboy/drone-ssh/releases/tag/v1.7.7
