### ISSUE TITLE
Cannot pull image

### ISSUE THREAD

**Issue by webfrank** [appleboy/drone-ssh#237]
I cannot pull the image anymore, this is the error

mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

**Comment by appleboy** [comment]
fix in https://github.com/appleboy/drone-ssh/commit/d0ed2bb2fbd0e68efe8da3db2df142c0ae4b8566 commit. please pull image again.
