### ISSUE TITLE
No such image: appleboy/drone-ssh:latest

### ISSUE THREAD

**Issue by webfrank** [appleboy/drone-ssh#241]
Error response from daemon: No such image: appleboy/drone-ssh:latest

running plugin in drone

**Comment by webfrank** [comment]
Hi,
  still this error:

bizmate@docker01:~/cloud-backup$ docker pull appleboy/drone-ssh
Using default tag: latest
latest: Pulling from appleboy/drone-ssh
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

**Comment by appleboy** [comment]
@webfrank Please try https://github.com/appleboy/drone-ssh/pkgs/container/drone-ssh
