### ISSUE TITLE
Support for dynamic target host group

### ISSUE THREAD

**Issue by noreebia** [appleboy/drone-ssh#270]
Hey, thanks for making this Drone plugin - we are using it almost every day at my workplace.

Would it be possible to enable support for hosts to be dynamically configured? Our AWS EC2 instances are created and destroyed depending on the traffic via auto scaling groups, so the list of target hosts are dynamic and not fixed.

It seems there was an attempt to do what I am explaining by a different contributor in this [issue](https://github.com/appleboy/drone-ssh/pull/156), but it seems to have been rolled back in this [commit](https://github.com/appleboy/drone-ssh/commit/7d0a88610981ab169372e3864b673cb9b6385b0f).

May I ask if there is any way for the target host group to be dynamically calculated on the fly?

**Comment by appleboy** [comment]
@noreebia Sorry about it. I will take it.
