### ISSUE TITLE
can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by andersonalz** [appleboy/drone-ssh#272]
Run appleboy/ssh-action@master
  with:
    host: ****
    username: root
    port: ****
    command_timeout: 2000m
    script: ****
  git checkout develop
  git pull
  docker compose down
  docker compose up -d --build
  
    protocol: tcp
    timeout: 30s
    proxy_port: 22
    proxy_timeout: 30s
Run echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
Run entrypoint.sh
Will download drone-ssh-1.7.4-linux-amd64 from https://github.com/appleboy/drone-ssh/releases/download/v1.7.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 5580k  100 5580k    0     0  7128k      0 --:--:-- --:--:-- --:--:-- 7128k
2024/04/28 08:49:20 Error: can't connect without a private SSH key or password

**Comment by andersonalz** [comment]
I want to deploy to the server but this error occurs

**Comment by appleboy** [comment]
You missing the password or private key.

> Error: can't connect without a private SSH key or password

your config:

```
host: ****
username: root
port: ****
command_timeout: 2000m
script: ****
```
