### ISSUE TITLE
Container tag 1.16.13 causes issues

### ISSUE THREAD

**Issue by abrain** [appleboy/drone-ssh#281]
It appears, that version 1.6.13 got accidentally tagged as 1.16.13 once. Renovate (and probably other dependency tools) suggests this image as an update, because the version number is bigger than 1.7.7.

Would it be possible to remove the 1.16 and 1.16.13 tags from Docker Hub and GHCR?

**Comment by appleboy** [comment]
Please try the https://github.com/appleboy/drone-ssh/releases/tag/v1.7.7 version

**Comment by abrain** [comment]
There's no issue with the content of the release itself, but with the tags for the container image.

Renovate Bot keeps suggesting to upgrade to v1.16.13, which looks newer than v1.7.7, e.g. https://github.com/alexmyt/PurpleSchool-NestJS/pull/72

But as far as I can tell, it was a typo while tagging v1.6.13:

![grafik](https://github.com/user-attachments/assets/adedc135-9768-4724-8d94-3b00124f3a95)

There might be people that upgraded to this v1.16 who won't get newer versions susggested until a v1.17 or v2 is released.
