### ISSUE TITLE
feat: flag / option to disable "err:" / "out:" prefix from logs

### ISSUE THREAD

**Issue by XavierChanth** [appleboy/drone-ssh#282]
I'm using appleboy/ssh-action and would like to use [GitHub Actions log grouping](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#grouping-log-lines) but the "out:" prefix interferes with the way github actions tags meta log lines:

Example ([from here](https://github.com/atsign-foundation/noports/actions/runs/10636659529/job/29488922210?pr=1299)):
```
out: ::group::Show build logs
... (lots of logs here - which most of the time we don't want to see)
out: ::endgroup::
```

I'm trying to introduce a bunch of these groups as we have a lot of log fragments for a bunch of different tests, which most of the time are going to be irrelevant (until something goes wrong!).

This is where these prefix strings are hardcoded:
```
https://github.com/appleboy/drone-ssh/blob/2041794fd5ecb825fa46d91024da84b62668bd0e/plugin.go#L146-L153
```

If you think this use-case / feature is useful to the project I'd be happy to raise PRs where necessary.

I was thinking there are a few ways in which this could be implemented:

1. A boolean flag to outright disable the log prefixes (e.g. `--no-log-prefixes`)
2. String options for each prefix, which default to the current hard-coded values
   (e.g. to disable prefixes: `--out-prefix=""` and `--err-prefix=""`)

I think 2. is a reasonable approach, but if you have a better approach I am open to feedback.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@XavierChanth I have removed the prefixes "out:" and "err:" in the latest version.

**Comment by XavierChanth** [comment]
> @XavierChanth I have removed the prefixes "out:" and "err:" in the latest version.
> 
> 

Thanks!
