### ISSUE TITLE
Merge stdout and stderr

### ISSUE THREAD

**Issue by jhasse** [appleboy/drone-ssh#64]
Currently output is shown in two parts: First normal output to stdout then "errors" (I guess this is what went to stderr).

Having multiple commands, this makes understanding the output quite hard as it isn't ordered chronology any more.

**Comment by appleboy** [comment]
@jhasse Can you help to test the latest image? Waiting for your feedback.

**Comment by jhasse** [comment]
Works, thank you! Awesome :)

I would go with `out:` and `err:` though, as it is shorter and then output is aligned correctly (`outputs:` and `errors:` have one character difference).

Also maybe remove the hostname in front of each line? My host is a rather long subdomain which moves everything to the right. Also the hostname is already at the beginning before `commands:`.

**Comment by appleboy** [comment]
@jhasse 

1. change `outputs:` to `out:` and `errors:` to `err:`
2. hide `hostname` if the single domain in drone setting. OK?

**Comment by jhasse** [comment]
Yes, sounds perfect :)
