### ISSUE TITLE
Streaming the output

### ISSUE THREAD

**Issue by Jean85** [appleboy/drone-ssh#69]
Currently, my SSH command (which is a deploy script) can take up to 120 seconds. I would like to see the output of my commands in real time, not just at the end... Is that possible?

Maybe this can be done in conjunction with #64

**Comment by appleboy** [comment]
@Jean85 Can you help to test the latest image? Waiting for your feedback.

**Comment by Jean85** [comment]
I works great, thanks!!
It's only a bit verbose because it prepends the timestamp on each line of output (and you have the elapsed seconds on the right on the Drone interface) but it's fantastic!

**Comment by appleboy** [comment]
@Jean85 I will remove the timestamp.

**Comment by appleboy** [comment]
@Jean85 Done. Please pull the latest image.

Screenshot:

![screen shot 2017-05-10 at 3 38 44 pm](https://cloud.githubusercontent.com/assets/21979/25887963/d626d294-3596-11e7-9bf5-882727cb8f21.png)

**Comment by Jean85** [comment]
Yes it works too.

**Comment by appleboy** [comment]
@Jean85 Done. Please update docker image.
