### ISSUE TITLE
Add strict option to throw error when remote command failed

### ISSUE THREAD

**Issue by ntoljic** [appleboy/drone-ssh#70]
The current implementation returns errors of remote commands in the log. Even with those errors the build step still passes. While I see the use case for such (default) behavior, I would love to be able to pass a `strict` option to the plugin. When this options is enabled, errors in the remote commands should result in the build step not passing.

**Comment by appleboy** [comment]
duplicated of https://github.com/appleboy/drone-ssh/issues/66

**Comment by ntoljic** [comment]
oh, sorry. Don't know how I missed that.
