### ISSUE TITLE
Handling secrets changed in Drone 0.6

### ISSUE THREAD

**Issue by Jean85** [appleboy/drone-ssh#82]
http://docs.drone.io/release-0.6.0-secrets#plugins

> Secrets are passed to pipeline steps (including plugins) as environment variables. Plugin authors must update their plugins to source secrets from specific environment variables.

I was using a secret to inject the SSH key in the YAML config. This doesn't work anymore.

**Comment by appleboy** [comment]
@Jean85 Please paste your drone config. It is working on my drone server (0.6 version).

**Comment by Jean85** [comment]
I have identical setup with SSH and SCP plugins:

  copy-deploy-script:
    when:
      branch: master
      status: success
    image: appleboy/drone-scp
    host: some.host.com
    username: user
    key: ${DEPLOY_SSH_KEY}
    secrets: [ DEPLOY_SSH_KEY ]
    target: /home/user
    source:
      - docker/docker-compose.yml.production
      - bin/deploy.sh

**Comment by appleboy** [comment]
```diff
copy-deploy-script:
    when:
      branch: master
      status: success
    image: appleboy/drone-scp
    host: some.host.com
    username: user
-   key: ${DEPLOY_SSH_KEY}
-   secrets: [ DEPLOY_SSH_KEY ]
+   secrets:
+     - source: DEPLOY_SSH_KEY
+       target: ssh_key
    target: /home/user
    source:
      - docker/docker-compose.yml.production
      - bin/deploy.sh
```

**Comment by Jean85** [comment]
Nope, still failing:

> ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by appleboy** [comment]
@Jean85 could you help to add the new secret key as `ssh_key`?

**Comment by Jean85** [comment]
Like this?

```diff
    host: blaine.facile.it
    username: blaine
+    secrets: [ ssh_key ]
```
Didn't work...

**Comment by appleboy** [comment]
Yes, you need to add the new secret key which name is `ssh_key` first.

--
About me: http://about.me/appleboy

**Comment by Jean85** [comment]
I did it, I didn't forget about it.
I also tried this, didn't work:

```diff
    username: user
+    key_path: /run/secrets/ssh_key
+    secrets:
+      - source: DEPLOY_SSH_KEY
+        target: ssh_key
+        mode: 0440
```

**Comment by Jean85** [comment]
Finally made it work:

```yaml
    secrets:
      - source: DEPLOY_SSH_KEY
        target: ssh_key
```

Some of the previous attempts failed because I was using the config with the SCP step, where the config is slightly different:

```diff
    secrets:
      - source: DEPLOY_SSH_KEY
-        target: ssh_key
-        target: scp_key
```
So, the name of the ENV variable must be composed by `scp`/`ssh` + `_` + `key`/`password`/etc
