### ISSUE TITLE
Shell Script not working

### ISSUE THREAD

**Issue by iveeshal** [appleboy/drone-ssh#88]
Trying this.  "try.sh" is at resources from where .drone.yml is present

resources/try.sh: No such file or directory

ssh:
    image: drone.docker.target.com/drone-ssh:1
    host: 10.63.166.248
    username:${ARTIFACTORY_USER}
    password: ${ARTIFACTORY_PASSWORD}
    port: 22
    command_timeout: 1800
    script:
      - ls -ltr
      - resources/try.sh

**Comment by appleboy** [comment]
What is your drone version? Please see the doc: http://plugins.drone.io/appleboy/drone-ssh/
